### ISSUE TITLE
download de camada

### ISSUE THREAD

**Issue by thomazrezende** [thomazrezende/wwf_lapig#11]
como ativar o download do arquivo espacial de uma camada?

**Comment by FernandaStefani** [comment]
Thomaz,

O download da camada pode ser feito através do serviço WFS com a requisição GetFeature, colocando alguns parâmetros, onde o principal deles é o TYPENAME que recebe o nome da camada a ser feito a Download. Padronizei da seguinte forma: id_ano, veja os exemplos:

**Area Soja 2015**
http://maps.lapig.iesa.ufg.br/ows?REQUEST=GetFeature&SERVICE=wfs&VERSION=1.0.0&TYPENAME=area_soja_2015&OUTPUTFORMAT=shape-zip

**Desmatamento 2005**
http://maps.lapig.iesa.ufg.br/ows?REQUEST=GetFeature&SERVICE=wfs&VERSION=1.0.0&TYPENAME=desmatamento_2005&OUTPUTFORMAT=shape-zip

**Trabalho Escravo 2009**
http://maps.lapig.iesa.ufg.br/ows?REQUEST=GetFeature&SERVICE=wfs&VERSION=1.0.0&TYPENAME=trabalho_escravo_2009&OUTPUTFORMAT=shape-zip

**Unidades de Conservação Integral**
http://maps.lapig.iesa.ufg.br/ows?REQUEST=GetFeature&SERVICE=wfs&VERSION=1.0.0&TYPENAME=unidades_conservacao_integral_2014&OUTPUTFORMAT=shape-zip
Essa camada possui somente um ano, mesmo assim o TYPENAME receberá o id_ano, para que fique padrão para todos os tipos de dados.

O que achou?

Qualquer dúvida me avise.
