### ISSUE TITLE
Download de dados  - indicadores selecionados

### ISSUE THREAD

**Issue by thomazrezende** [thomazrezende/wwf_lapig#14]
link de acesso para lista de indicadores mostrando dados apenas dos indicadores selecionados

**Comment by thomazrezende** [comment]
formato csv

**Comment by FernandaStefani** [comment]
Thomaz, estou saindo de férias hoje (Meu voo é daqui a pouco rsrs), infelizmente não vai dar tempo de lançar o recurso de Download nessa primeira versão que será lançada dia 25. Isso poderá ser implementado assim que eu retornar na primeira semana de julho.
