### ISSUE TITLE
transparencia para valores nulos

### ISSUE THREAD

**Issue by thomazrezende** [thomazrezende/wwf_lapig#16]
quando um mapa de cores chapadas for carregado, o preenchimento deve ser removido dos municípios com valor nulo.

ex: trabalho escravo

![screen shot 2017-07-05 at 16 55 56](https://user-images.githubusercontent.com/8996819/27882389-dcedf4f8-61a2-11e7-8e12-91005d3e728e.png)

**Comment by FernandaStefani** [comment]
Concluído!
