### ISSUE TITLE
ranking da seleção no relatório

### ISSUE THREAD

**Issue by thomazrezende** [thomazrezende/wwf_lapig#19]
Mostrar ranking de municípios para cada indicador dentro do filtro espacial corrente na mesma solicitação da lista de indicadores.

**Comment by thomazrezende** [comment]
10 maiores e 10 menores de cada indicador para aquela seleção 

DADOS POR MUNICÍPIO
- nome do município
- UF
- valor do indicador
- posição no ranking

**Comment by thomazrezende** [comment]
CASO A SELEÇÃO ESPACIAL SEJA UM MUNICÍPO:

a posição desse município no ranking + dados dos 10 anteriores e dos 10 posteriores

**Comment by FernandaStefani** [comment]
Thomaz,

Este serviço está pronto, conforme combinamos. O parâmetros para acessá-lo são região e ano, vou enviar alguns exemplos por aqui para que facilite o entendimento de como utilizar. O Município trará dois rankings diferentes:
"ranking": Posição do município comparado a todos do Brasil,
"rankingUF": Posição do município comparado a todos do seu estado.

O restante das regiões possuem somente um ranking ligado a região e ano, com os 10 primeiros municípios e 10 últimos do ranking.
Veja como ficou o serviço:

**Brasil, 2014:**
http://maps.lapig.iesa.ufg.br/indicadores/lista?ano2014

**Estado de Goiás, 2010:**
http://maps.lapig.iesa.ufg.br/indicadores/lista?regionType=estado&region=GO&ano=2010

**Bioma Cerrado, 2008:**
http://maps.lapig.iesa.ufg.br/indicadores/lista?regionType=bioma&region=CERRADO&ano=2008

**Região MATOPIBA, 2015:**
http://maps.lapig.iesa.ufg.br/indicadores/lista?regionType=regiao&region=MATOPIBA&ano=2015

**Município de Sorriso - MT, 2014:**
http://maps.lapig.iesa.ufg.br/indicadores/lista?regionType=municipio&region=5107925&ano=2014

**A posição do Município em relação ao Brasil é indicada pela propriedade: RKmunicipioBR
**A posição do Município em relação ao Estado é indicada pela propriedade: RKmunicipioUF

Qualquer dúvida por favor me avise.

**Comment by FernandaStefani** [comment]
Oi Thomaz,

Achei o erro, era no próprio link que eu enviei, estava faltando o sinal de "=" no ano, segue o link correto para o Brasil em 2014:
http://maps.lapig.iesa.ufg.br/indicadores/lista?ano=2014

**Comment by thomazrezende** [comment]
Oi @FernandaStefani 

acabei de me dar conta de uma coisa: a data do ranking faz sentido no indicador específico e não na lista toda de indicadores, pois em cada indicador podemos selecionar um ano diferente. Desculpe, esse foi erro meu, pois pedi que o ranking viesse junto com a solicitação da lista, mas isso não funciona. Os rankings são gerados no momento em que clico no botão gerar_relatório e não quando solicito a lista completa de indicadores (que é feita bem antes disso). Isso inclusive pode sobrecarregar o servidor de vcs. Quando tivermos todos os indicadores ele fará o calculo do ranking para todos, independente do que será selecionado.

Enfim, quero estudar a possibilidade de separarmos esse request para que eu faça um novo request só para os rankings. O ideal é que ele considere 1. os indicadores selecionados, 2. o ano ativo para cada indicador selecionado e 3. a área ativa. Ou seja, será um request com um parâmetro extra em cada.

Desculpe só perceber isso agora. Vamos conversar quando vc puder para analisarmos as possibilidades

abs

**Comment by thomazrezende** [comment]
outra possibilidade é o ranking considerar sempre a média dos valores em todos os anos disponíveis para o indicador. Talvez isso também carregue demais o servidor na hora dos requests, pois teríamos que calcular todas as médias antes de montar a lista, mas pelo menos daria pra manter a estrutura atual sem precisar de novos requests a cada relatório. Inclusive acho esse dado mais interessante do ponto de vista analítico, pois daria uma visão mais ampla e livre de desvios de anos atípicos.

o que poderia resolver o problema do excesso de calculos é termos essas médias pré-calculadas no banco. Assim a ordenação usaria a estrutura que vc ja criou e o request ficaria mais leve

**Comment by FernandaStefani** [comment]
Oi Thomaz,

O serviço está pronto, espero que agora ele consiga atender.
Eu pensei em uma requisição para cada indicador, para que não pese um serviço por se só, e como um relatório vai trazer um ranking para cada indicador, na minha visão assim fica funcional.

Veja como está funcionando:

Ranking de **Área Plantada de Soja** para todo o Brasil no ano de **2015**:
http://maps.lapig.iesa.ufg.br/indicadores/ranking?id=area_soja&ano=2015

Ranking de **Desmatamento** para o bioma **Cerrado** em **2010**:
http://maps.lapig.iesa.ufg.br/indicadores/ranking?id=desmatamento&ano=2010&regionType=bioma&region=CERRADO

Ranking de **Trabalho Escravo** para a região do **Arco do Desmatamento** em **2012**:
http://maps.lapig.iesa.ufg.br/indicadores/ranking?id=trabalho_escravo&ano=2012&regionType=regiao&region=Arco%20do%20Desmatamento

Ranking de **Unidades de Conservação de Proteção Integral** para o estado de **Goiás** em **2014**:
http://maps.lapig.iesa.ufg.br/indicadores/ranking?id=unidades_conservacao_integral&ano=2014&regionType=estado&region=GO

Ranking de **Área Plantada de Soja** para o município de **Sorriso** em **2013**:
http://maps.lapig.iesa.ufg.br/indicadores/ranking?id=area_soja&ano=2013&regionType=municipio&region=5107925

Os parâmetros passados serão:
id=
ano=
regionType=
region=
**Exceto para o Brasil que não precisa de indicar a região.

Acredito que agora irá lhe atender, pois você poderá utilizar o id do indicador selecionado e o ano selecionado.

Faça um teste e me avise.
Já posso retirar o ranking do serviço de /lista?

Obrigada!

**Comment by thomazrezende** [comment]
ola @FernandaStefani. Obrigado, vou fazer um teste agora e te aviso se tiver algum problema. Pode remover o ranking da lista

**Comment by thomazrezende** [comment]
funcionou! obrigado ;)

![screen shot 2017-08-02 at 20 44 21](https://user-images.githubusercontent.com/8996819/28899768-6265baf4-77c3-11e7-8d29-7c60cc744c35.png)
