### ISSUE TITLE
Clique no município

### ISSUE THREAD

**Issue by thomazrezende** [thomazrezende/wwf_lapig#2]
Clique no mapa deve carregar dados do município com as informações

- nome do município
- estado
[ para cada indicador ativo ]
- dado daquele indicador no ano escolhido
- (se houver mais dados por ano) dados dos outros anos para construção de gráfico 
- posição que município ocupa no ranking do indicador comparado aos **outros municípios da seleção espacial corrente**. Importante que o ranking sempre leve em consideração a seleção espacial, pois só assim será possível comparar municípios de um mesmo estado, mesmo bioma, mesma bacia ou todos do Brasil (sem filtro espacial).
- O ranking deve apresentar o nome-UF dos 10 municípios adjacentes (5 acima e 5 abaixo) para construção de lista
[ fim indicadores ]

**Comment by FernandaStefani** [comment]
Oi, Thomaz,

Esse Issue também é possível de entregarmos a você nessa versão.
Eu vou construir um exemplo e te envio. Também peço até o dia 16/06 para entrega, porém acredito que consiga lhe enviar antes.

Obrigada!

**Comment by FernandaStefani** [comment]
Thomaz,

O UTF-Grid se mostrou bastante complexo, tentamos de tudo para lhe enviar ele funcionando com a aplicação mas infelizmente não foi possível. Meu Voo é daqui a pouco e me dediquei cada minuto para fazê-lo funcionar mas infelizmente ele precisa de mais ajustes técnicos como a criação de um drive que já demos início. A continuação sera possível assim que eu retornar de ferias na primeira semana de julho, vou tirar somente alguns dias essa viagem já estava programada desde o início do ano, infelizmente não consigo remarcar. O UTF-grid poderá dar um visual bem bacana para aplicação por isso nossa insistência de usá-lo, vamos conseguir fazê-lo funcionar, porém não para essa versão do dia 25/06, na semana que eu retornar que já é a seguinte do lançamento, darei continuidade ao desenvolvimento imediatamente.

**Comment by thomazrezende** [comment]
exemplo do UTF-GRID + verificar se há como diferenciar clique de drag, evitando cliques acidentais no arrastar do mapa

**Comment by FernandaStefani** [comment]
Acredito que esse já está resolvido com a nova questão que definimos do UTFGrid.
