### ISSUE TITLE
estado do Ceará aparece duplicado

### ISSUE THREAD

**Issue by thomazrezende** [thomazrezende/wwf_lapig#22]
![screen shot 2017-07-28 at 21 23 48](https://user-images.githubusercontent.com/8996819/28740449-215001dc-73db-11e7-8bce-a388357caba1.png)

**Comment by thomazrezende** [comment]
@FernandaStefani parece que o estado do espirito santo está com o label "ceará" no banco de vcs, pois, alem da duplicidade aciam, quando seleciono aparece isso no mapa:

(alias, consegui fazer a mascara limits aparecer :)

![screen shot 2017-07-28 at 21 28 45](https://user-images.githubusercontent.com/8996819/28740510-f1e7ea30-73db-11e7-944c-d12ef58714ee.png)

**Comment by FernandaStefani** [comment]
Oi Thomaz, estranho...
Estarei verificando no Banco de Dados, obrigada pela observação.

**Comment by FernandaStefani** [comment]
Thomaz, boa noite!

O erro foi corrigido, era o nome do estado que estava incorreto mesmo. Através da UF foi simples corrigir.

Obrigada!
