### ISSUE TITLE
area_filter estabelecer fitBounds no WMS

### ISSUE THREAD

**Issue by thomazrezende** [thomazrezende/wwf_lapig#24]
Seria interessante que o mapa focasse na área escolhida após o carregamento dos dados. O problema é o mapa WMS não possui um shape que possa ser usado para calcular essa posição + zoom. Uma possibilidade é o sistema retornar as coordenadas do centro geométrico das seleções junto com os dados, independente se estamos falando de um estado ou município. Esse dado existe @FernandaStefani? O zoom teria que ser estimado de acordo com o regionType. 

algo asssim:

![screen shot 2017-07-31 at 17 49 40](https://user-images.githubusercontent.com/8996819/28798007-9278e8e8-7619-11e7-8362-c7efae7728a9.png)

**Comment by FernandaStefani** [comment]
Thomaz, vou verificar isso e te retorno.

**Comment by thomazrezende** [comment]
@FernandaStefani, como isso surgiu na reunião vou colocar como prioridade ok?

**Comment by thomazrezende** [comment]
Oi @FernandaStefani

duas questões surgiram sobre esse recurso:

1. eu queria o fit bounds em torno da área selecionada e não em torno do shape da camada. No exemplo acima estou focando na mascara do Acre. O importante é localizar o usuário no mapa quando ele escolher uma área, que quando for um município, pode ficar difícil de encontrar. O recurso para a camada já está feito e podemos até manter, mas preciso que seja feito para as áreas tb. Não encontrei o dado bbox na resposta da mascara.

2. Testando o serviço no carregamento da camada ocorreu um problema aqui: Apareceu essa mensagem de erro e não consegui identificar por que:

leaflet.js:5 Uncaught RangeError: Maximum call stack size exceeded
    at o.LatLngBounds.extend (leaflet.js:5)
    at new o.LatLngBounds (leaflet.js:5)
    at Object.o.latLngBounds (leaflet.js:5)
    at o.LatLngBounds.extend (leaflet.js:5)
    at new o.LatLngBounds (leaflet.js:5)
    at Object.o.latLngBounds (leaflet.js:5)
    at o.LatLngBounds.extend (leaflet.js:5)
    at new o.LatLngBounds (leaflet.js:5)
    at Object.o.latLngBounds (leaflet.js:5)
    at o.LatLngBounds.extend (leaflet.js:5)

**Comment by FernandaStefani** [comment]
Oi Thomaz,

O zoom é dado na área do mapa e não necessariamente na camada, pois se você ajusta o mapa para a região desejada a camada também segue o mesmo caminho. E para que a camada apareça apenas na área selecionada, basta utilizar o MSFILTER. O zoom você precisa dar apenas no mapa (map), e não na camada específica (ex: area_soja), conforme no exemplo que te enviei.

Não sei se foi isso mesmo que você quis dizer, aguardo sua resposta.
