### ISSUE TITLE
área do elemento selecionado

### ISSUE THREAD

**Issue by thomazrezende** [thomazrezende/wwf_lapig#27]
Recurso sugerido pela Roberta: incluir o valor da área total (em ha) do elemento selecionado para que eu possa calcular a porcentual de cada indicador na lista de indicadores (onde se aplicar). Para isso preciso que esse numero venha no json da lista de indicadores

**Comment by thomazrezende** [comment]
@FernandaStefani vou colocar na prioridade porque entendi que era simples. Se for atrapalhar muito deixamos para a v2

**Comment by FernandaStefani** [comment]
Prontinho!

**Comment by FernandaStefani** [comment]
Chave "area_ha" em indicadores/lista
