### ISSUE TITLE
Seleção espacial : novo método

### ISSUE THREAD

**Issue by thomazrezende** [thomazrezende/wwf_lapig#3]
A seleção de filtro espacial não teria mais o recurso de confinar o mapa dentro da área selecionada (como temos hoje). A escolha de determinada camada passaria a trazer sempre o shape/mapa para o brasil todo e ofereceria sempre essa camada sem cortes para download, independente da seleção espacial. A filtragem espacial precisa oferecer dois recursos:

1. continuar trazendo dados numéricos filtrados para construção da lista de indicadores + dados da área escolhida (como temos hoje)
2. Criaria no mapa um novo layer com o contorno da área escolhida (recurso novo)
3. Modifica zoom e centro do mapa, posicionando a área escolhida no centro da tela

Portanto a configuração Region e RegionType continua existindo, mas interfere apenas nos dados numéricos. No mapa, interfere criando esse destaque visual em torno da área em destaque. 

Exemplo:
A escolha do indicador DESMATAMENTO para o estado de Goiás vai me trazer o shape de desmatamento no Brasil todo e, sobre ele, um layer com o contorno do estado de Goiás (apenas stroke). Na lista de indicadores, o valor exibido nas caixas dos indicadores será apenas para o estado de Goiás.

![exemplo_selecao](https://user-images.githubusercontent.com/8996819/26950762-2ad2ec7a-4c75-11e7-983c-3353023ab827.jpg)

**Comment by FernandaStefani** [comment]
Oi Thomaz,

Já estudei a proposta e é perfeitamente possível implementar o novo método de seleção espacial. Peço até o dia 16/06 como prazo para entrega. Mas caso consiga finalizar antes, lhe envio.

Obrigada!

**Comment by thomazrezende** [comment]
Vamos fazer essa linha com 4px de espessura e preta 80% (#333333) ok?

**Comment by FernandaStefani** [comment]
Thomaz, boa noite!

Já está funcionando, adicionei mais 4 regions:
**regions_in** : Região completa de todo o Brasil a única que inclui os Municípios.
**regions_arco**: Região do arco do desmatamento.
**regions_biomas**: Região com todos os Biomas.
**regions_estados**: Região com todos os Estados.
**regions_matopiba**: Região de todo o Matopiba.

Para carregá-lo é conforme qualquer camada camada, veja:

Município de Goiânia:
http://maps.lapig.iesa.ufg.br/ows?Layers=regions_in&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8200300,-3996220,-3190922.915,1013157.085&WIDTH=512&HEIGHT=512&MSFILTER=%22[COD_MUNICI]%22=%225208707%22

Arco do Desmatamento:
http://maps.lapig.iesa.ufg.br/ows?Layers=regions_arco&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8200300,-3996220,-3190922.915,1013157.085&WIDTH=512&HEIGHT=512

Bioma Cerrado:
http://maps.lapig.iesa.ufg.br/ows?Layers=regions_biomas&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8200300,-3996220,-3190922.915,1013157.085&WIDTH=512&HEIGHT=512&MSFILTER=%22[NM_BIOMA]%22=%22CERRADO%22

Estado de Goiás:
http://maps.lapig.iesa.ufg.br/ows?Layers=regions_estados&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8200300,-3996220,-3190922.915,1013157.085&WIDTH=512&HEIGHT=512&MSFILTER=%22[NM_UF]%22=%22GO%22

Matopiba:
http://maps.lapig.iesa.ufg.br/ows?Layers=regions_matopiba&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8200300,-3996220,-3190922.915,1013157.085&WIDTH=512&HEIGHT=512

Obs. Somente a região do Arco do Desmatamento e Matopiba não precisam de filtros (MSFILTER).

Qualquer dúvida me avise.

**Comment by thomazrezende** [comment]
Fernanda, não consegui aplicar esse método. Quando vc voltar, vou precisar da sua ajuda para implementaremos esse recurso

alem disso estranhei a logica de seleção dos itens. Na seleção de dados temos region e regionType como variáveis para montar as diferentes queries, mas aqui cada grupo tem uma lógica própria. Ainda mais, matopiba e Arco do desmatamento (que são ambos do tipo "Região"), possuem uma url cada. Isso vai dificultar muito a implementação / atualização

**Comment by thomazrezende** [comment]
priorizar o exemplo funcional em html

**Comment by FernandaStefani** [comment]
Thomaz, boa tarde!

Consegui construir todo o limite espacial em uma só camada, imagino que assim ficará mais fácil de implementá-lo. O nome da camada é "**limits**" e você poderá filtrá-la por 
"**name**"(CERRADO, GO, 3550308, ARCODESMATAMENTO, MATOPIBA) ou por "**type**" (BIOME, STATE, CITY, ROI).
O shape foi organizado com todos os limites de regiões que utilizamos no momento. Segue alguns exemplos de filtro, para ter uma ideia melhor:

**Bioma Cerrado:**
http://maps.lapig.iesa.ufg.br/ows?Layers=limits&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8200300,-3996220,-3190922.915,1013157.085&WIDTH=512&HEIGHT=512&MSFILTER=%22[name]%22=%22CERRADO%22

**Estado de Goiás:**
http://maps.lapig.iesa.ufg.br/ows?Layers=limits&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8200300,-3996220,-3190922.915,1013157.085&WIDTH=512&HEIGHT=512&MSFILTER=%22[name]%22=%22GO%22

**Município de São Paulo:**
http://maps.lapig.iesa.ufg.br/ows?Layers=limits&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8200300,-3996220,-3190922.915,1013157.085&WIDTH=512&HEIGHT=512&MSFILTER=%22[name]%22=%223550308%22

**Arco do Desmatamento:**
http://maps.lapig.iesa.ufg.br/ows?Layers=limits&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8200300,-3996220,-3190922.915,1013157.085&WIDTH=512&HEIGHT=512&MSFILTER=%22[name]%22=%22ARCODESMATAMENTO%22

**Matopiba:**
http://maps.lapig.iesa.ufg.br/ows?Layers=limits&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8200300,-3996220,-3190922.915,1013157.085&WIDTH=512&HEIGHT=512&MSFILTER=%22[name]%22=%22MATOPIBA%22

**Limites estaduais do Brasil:**
http://maps.lapig.iesa.ufg.br/ows?Layers=limits&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8200300,-3996220,-3190922.915,1013157.085&WIDTH=512&HEIGHT=512&MSFILTER=%22[type]%22=%22STATE%22

**Limites dos Biomas do Brasil:**
http://maps.lapig.iesa.ufg.br/ows?Layers=limits&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&SERVICE=WMS&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8200300,-3996220,-3190922.915,1013157.085&WIDTH=512&HEIGHT=512&MSFILTER=%22[type]%22=%22BIOME%22

Como você pode ver, o filtro é dado pela tag "name", que você poderá colocar o nome de um Bioma, a UF de um estado, o Código do Município de um Município, uma região de interesse (ROI) como o MATOPIBA ou Arco do Desmatamento.

A forma de implementação é igual a inserção de uma camada no mapa, o fato é que essa camada ficará por cima das outras. Se quiser ver um exemplo de como usamos basta acessar o portal (http://maps.lapig.iesa.ufg.br/), dá uma olhadinha na ferramenta de "Inteligência Territorial", ele faz exatamente isso, quando o usuário seleciona uma região a camada "regions" é carregada no mapa com o filtro da região aplicado.

P.s. Esse %22 da URL são as aspas duplas.

Qualquer dúvida, me avise.
