### ISSUE TITLE
Hospedagem

### ISSUE THREAD

**Issue by thomazrezende** [thomazrezende/wwf_lapig#4]
Seria interessante a gente já ir preparando a área de hospedagem, registro de dominio etc. É bom para fazermos os testes e pra não deixar para a última hora. 

Imaginei o dominio riscosocioambiental.com / riscosocioambiental.org, mas essa decisão deve ser tomada por vcs (Lapig + WWF)

**Comment by FernandaStefani** [comment]
Thomaz, o Leandro poderá lhe prestar todo apoio na hospedagem e cadastro de domínio. Enviarei um e-mail a vocês.
