### ISSUE TITLE
CORES

### ISSUE THREAD

**Issue by thomazrezende** [thomazrezende/wwf_lapig#5]
Abaixo algumas paletas para uso nas camadas. Estou optando por cores sequenciais (variações de tonalidade de uma mesma cor ou cores próximas), para que tenhamos uma visualização com mais contraste entre as camadas e menos contraste entre elementos de uma mesma camada. Quando a camada não exigir mais do que uma cor, podemos adotar a cor central, mas quando exigir, vamos usar alguma das paletas abaixo:

['#f7fcfd','#e5f5f9','#ccece6','#99d8c9','#66c2a4','#41ae76','#238b45','#006d2c','#00441b']
![screen shot 2017-06-14 at 20 38 38](https://user-images.githubusercontent.com/8996819/27159196-b2eae286-5141-11e7-8085-88035be63021.png)

['#f7fcfd','#e0ecf4','#bfd3e6','#9ebcda','#8c96c6','#8c6bb1','#88419d','#810f7c','#4d004b']
![screen shot 2017-06-14 at 20 38 43](https://user-images.githubusercontent.com/8996819/27159200-b606644a-5141-11e7-8200-62500a85c9fa.png)

['#f7fcf0','#e0f3db','#ccebc5','#a8ddb5','#7bccc4','#4eb3d3','#2b8cbe','#0868ac','#084081']
![screen shot 2017-06-14 at 20 38 55](https://user-images.githubusercontent.com/8996819/27159208-bfe501ba-5141-11e7-896b-e0c6468d3305.png)

['#fff7ec','#fee8c8','#fdd49e','#fdbb84','#fc8d59','#ef6548','#d7301f','#b30000','#7f0000']
![screen shot 2017-06-14 at 20 38 59](https://user-images.githubusercontent.com/8996819/27159209-c2c82a56-5141-11e7-8d30-10a2abdb261f.png)

['#fff7fb','#ece7f2','#d0d1e6','#a6bddb','#74a9cf','#3690c0','#0570b0','#045a8d','#023858']
![screen shot 2017-06-14 at 20 39 03](https://user-images.githubusercontent.com/8996819/27159210-c5387af2-5141-11e7-8ca7-ea7a3a79b425.png)
   
['#f7f4f9','#e7e1ef','#d4b9da','#c994c7','#df65b0','#e7298a','#ce1256','#980043','#67001f']
![screen shot 2017-06-14 at 20 39 41](https://user-images.githubusercontent.com/8996819/27159216-caf5418c-5141-11e7-897f-73f9f6c3bbe5.png)

['#fff7f3','#fde0dd','#fcc5c0','#fa9fb5','#f768a1','#dd3497','#ae017e','#7a0177','#49006a']
![screen shot 2017-06-14 at 20 39 45](https://user-images.githubusercontent.com/8996819/27159218-cd50f5ac-5141-11e7-88ac-ea6772be4e53.png)

['#ffffe5','#f7fcb9','#d9f0a3','#addd8e','#78c679','#41ab5d','#238443','#006837','#004529']
![screen shot 2017-06-14 at 20 39 49](https://user-images.githubusercontent.com/8996819/27159221-d1f40658-5141-11e7-949d-0d81bada76c4.png)

['#ffffd9','#edf8b1','#c7e9b4','#7fcdbb','#41b6c4','#1d91c0','#225ea8','#253494','#081d58']
![screen shot 2017-06-14 at 20 39 53](https://user-images.githubusercontent.com/8996819/27159223-d51d722e-5141-11e7-95bc-869e6c48727d.png)

['#ffffe5','#fff7bc','#fee391','#fec44f','#fe9929','#ec7014','#cc4c02','#993404','#662506']
![screen shot 2017-06-14 at 20 39 56](https://user-images.githubusercontent.com/8996819/27159226-d78e3c50-5141-11e7-9abb-b74de039db09.png)

**Comment by FernandaStefani** [comment]
Oi Thomaz,

Atualizei os estilos das cores das camadas:
Trabalho Escravo: Verde (Primeiro)
Unidade de Conservação: #084081 (coloquei uma cor mais forte por causa dos traços mais finos)
Desmatamento: #fe9929
Plantação de Soja: Tentei fazer com os símbolos, porém o MapServer não está aceitando ele colore do mesmo jeito, há alguns formatos de legenda que ele não aceita. Neste caso coloquei cores em primeira solução, porém assim que retornar vou tentar colocar o símbolo assim como combinado.

Obrigada!
