### ISSUE TITLE
Lista completa de indicadores

### ISSUE THREAD

**Issue by thomazrezende** [thomazrezende/wwf_lapig#7]
Por enquanto temos apenas aqueles 4 indicadores de exemplo sendo carregados no acesso ao banco de dados. Quando teremos a lista completa?

**Comment by FernandaStefani** [comment]
Assim que retornar de viagem na primeira semana de Julho podemos estudar isso e definir uma lista completa para a próxima versão, ou só atualizar essa.

**Comment by FernandaStefani** [comment]
A lista completa neste momento é essa: https://docs.google.com/spreadsheets/d/1R3W5Yn5w27HdinZWSZnYOjzY4CCdFdVIf1mr9EciC2M/edit?usp=sharing

**Comment by FernandaStefani** [comment]
Estamos organizando, a Carolina nos retornou com as camadas que ela julgou necessárias.
Como te disse é algo simples de ser implementado pois internamente já estará tudo funcionando, só faremos a alteração do banco de dados. Até no meio da semana que vem conseguimos estar com isso finalizado, você acha interessante colocar todos os dados nessa primeira versão? Ou seria melhor algo mais "limpo" só com os 4 indicadores? Pois pelo que entendi da Carolina, eles estão esperando uma versão piloto ainda, não a versão completa.

**Comment by thomazrezende** [comment]
Legal @FernandaStefani.

Sim, acho bom termos mais camadas do que essas 4, também para podermos testar com outros exemplos. Mas vamos focar nas camadas que a Carolina escolheu. Não tem problema esperarmos até a semana que vem.

**Comment by FernandaStefani** [comment]
Combinado!!

**Comment by FernandaStefani** [comment]
Finalmente!! Finalizado 50GB de banco de dados rsrs
